name: 'Auto update'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  try_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: WingsZeng/go-auto-deps-action@v1
        with:
          repo_owner: 'SagerNet'
          repo_name: 'sing-box'
